######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 7 17:40:11 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += sql
HEADERS += class.h common.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += class.cpp main.cpp mainwindow.cpp
